### ISSUE TITLE
Pull done - status summary

### ISSUE THREAD

**Issue by sdalgard** [HEADS-project/sintefboard#2]
Hi,
Thank you for the update. 
It is now pulled into main branch.
It has been through a major refactoring ... hopefully easier to understand and maintain.

Maybe I was too fast with the pull....
You wrote that it was some remaining refactoring in "SerialInterpreter.java" it seems that most of it is commented.

**Comment by sdalgard** [comment]
In the class "Adaptations2Commands" I see that you create objects for each command that is to be sent to the device.
My question is if the sequence is predictable.
    If a channel shall be created the tasks has to be instantiated first.

I guess that the sequence depends on "for (AdaptationPrimitive p : model.getAdaptations())"
   To my knowledge is this sequence not defined in Java.
If this is the case we can sort the elements in "List<SerialCommand> cmds" before sending in to the device.

**Comment by maxleiko** [comment]
Yes, true. Forgot that.
You can find the "order" there https://github.com/kevoree/kevoree-js/blob/master/library/kevoree-node-javascript/lib/AdaptationEngine.js#L21 (lesser means higher priority)
(This is from the AdaptationEngine of the JavascriptNode)

**Comment by sdalgard** [comment]
Ok, then we have control of the sequence.
 ... in the last resort => HaraKiri

**Comment by maxleiko** [comment]
Yes :)

**Comment by brice-morin** [comment]
I made an attempt to order the commands

**Comment by sdalgard** [comment]
Thanks :+1:
