### ISSUE TITLE
What is expected to happen when connected to a board with running tasks/channels

### ISSUE THREAD

**Issue by sdalgard** [HEADS-project/sintefboard#9]
I am not sure if this is a supported use case or if it is a fault.
I would expected that the interpreter would build a model showing the current tasks/channels on the sintefboard.
The node as today detects that there are running processes.
It then tries to start the same processes once more ...

The use case we have tested up to now is a model pushed from the keveditor.
Now the interpreter is building the model based on infromation about tasks/channels from the sintefboard itself.
It seems that this buildup not is working as expected.

The task instance is not found and the interpreter tries to create it.
When information about the channel comes it does not find the ports for the specific task instance.

Whether it is a fault or not we should agree on wanted behaviour...

00:05 INFO: {} PROMPT HEADS->norm> task active
00:05 INFO: {} PROMPT Listing of current task instances
00:05 INFO: {} PROMPT Task type=sender instance=send state=RUN
00:05 INFO: Task instance <send> not found ... creating
00:05 INFO: {} PROMPT Task type=rxlcd instance=lcd state=RUN
00:05 INFO: Task instance <lcd> not found ... creating
00:05 INFO: {} PROMPT End of task instance listing
00:06 INFO: {} PROMPT HEADS->norm> channel list
00:06 INFO: {} PROMPT Listing of channels connected to current task instances
00:06 INFO: {} PROMPT Taskinstance=send port=tx0 ==> Taskinstance=lcd port=rx2
00:06 INFO: {} Component ports not found ... channel skipped
00:06 INFO: {} tx_port=null
00:06 INFO: {} rcv_port=null
00:06 INFO: {} PROMPT Taskinstance=lcd port=rx2 ==> Taskinstance=send port=tx0
00:06 INFO: {} Component ports not found ... channel skipped
00:06 INFO: {} tx_port=null
00:06 INFO: {} rcv_port=null
00:06 INFO: {} PROMPT End of channel listing
00:06 INFO: JavaNode received a new Model to apply from /nodes[node0]/components[comp804]
00:06 INFO: JavaNode Update completed in 22 ms
00:06 INFO: End deploy result=true-1
00:06 INFO: End of channel listing call to modelService.update() => applied=true
00:06 INFO: TaskInstantiate(rxlcd,lcd)
00:06 INFO: TaskRun(lcd)
00:06 INFO: TaskInstantiate(sender,send)
00:06 INFO: TaskRun(send)
00:06 INFO: Process done with 4 commands
00:07 INFO: {} PROMPT HEADS->norm> task instantiate rxlcd lcd
00:07 INFO: {} PROMPT Error instance_name=lcd is already in use
00:07 INFO: {} PROMPT  Command error! Check parameters.
00:08 INFO: {} PROMPT HEADS->norm> task instantiate sender send
00:08 INFO: {} PROMPT Error instance_name=send is already in use
00:08 INFO: {} PROMPT  Command error! Check parameters.
00:09 INFO: {} PROMPT HEADS->norm> task run lcd
00:09 INFO: {} PROMPT Task=rxlcd instance=lcd Resumed
00:10 INFO: {} PROMPT HEADS->norm> task run send
00:10 INFO: {} PROMPT Task=sender instance=send Resumed

**Comment by maxleiko** [comment]
Not sure to understand what the problem is. Can you make a step-by-step list of actions that leads to your problem?

**Comment by brice-morin** [comment]
Maybe I am wrong, but it seems so far we tried a top-down approach where we push a Kevoree model to an empty board (which would correspond to the initial deployment)

Now, we want to try a bottom-up approach where the board has already been installed, etc with some components and channels running (potentially updated outside of Kevoree, while the PC was not connected to the board via USB). Now, let's say for maintenance, we plug the PC to the board, and we would like to pull the current model out of the board, into a nice Kevoree model, which we can then update, etc (back to top-down approach).

**Comment by sdalgard** [comment]
Yes, Brice you are right

1) I have made a setup on the sintefboard using a terminalemulator having two tasks and a channel:
HEADS->norm> task in sender send
HEADS->norm> task in rxlcd lcd
HEADS->norm> channel cr send tx0 lcd rx2
HEADS->norm> task run

2) I disconnect the teminalemulator
3) Start the Kevoree system "mvn kev:run" without any model for the sintefboard
     The interpreter starts to scan the sintefboard and find the processes.
     This is the trace pasted in the start of this issue.

This sequence can be relevant if the kevoree system is restarted, or if the sintefboard is offline for a period.

**Comment by maxleiko** [comment]
Okay, well, you are running an "empty" Kevoree runtime (just a JavaNode and your component). So, after the interpretation of the state of the board, it creates a bunch of new entities and merge them.  
Now those entities are new from the "Kevoree" point-of-view, so it creates commands regarding those adaptations.  
And then, it sends those commands back to the board.

The problem is on the component, you should add a dictionnary attribute to SintefModComponent that specify a **behavior**. A boolean is enough IMO. Something like:

``` txt
add node0 : JavaNode
add node0.myComp : SintefModComponent

set node.myComp.applyCommands = 'false'
```

So, by default, it will update the Kevoree model, but then it will check if the `applyCommands` param is `true`, if it is, it sends the commands back to the board, otherwise it does nothing.

Feel right ?

**Comment by maxleiko** [comment]
A quick fix in `SintefModComponent.java` would be:

``` java
@ComponentType
public class SintefModComponent implements ModelListener {

    @Param(defaultValue = true)
    private boolean applyCmds;

    // ...

    public void modelUpdated() {
        if (applyCmds) {
          List<SerialCommand> cmds = adaptations2Commands.process(adaptationModel, channelChecker);
          Iterator<SerialCommand> it = cmds.iterator();
          SerialCommand cmd;
          while (it.hasNext()) {
              try {
                  cmd = it.next();
                  //Log.info("Send-to-serial: ("+cmd.priority()+")<" + cmd.toString() + ">");
                  interpreter.resetInterpreter(); // Tell the interpreter.receiver that the board is reconfigured
                  serialLink.writeBytes(cmd.toString().getBytes());
              } catch (SerialPortException e) {
                  Log.error("Unable to write to serial port (reason: {})", e.getMessage());
              }
          }
        } else {
          Log.info("Component is in 'update' mode only, commands will not be applied on the board");
        }
    }
}
```

**Comment by sdalgard** [comment]
Do you assume that the SintefModComponent has two modes?
   applyCmds == false  // Build model from sintefboard and make it available for "pull"  
   applyCmds == true  // Discard setup on board and wait for "push"

Is it possible to think something in between?
   "pull" model from sintefboard => make additions => "push" new model onto sintefboard

**Comment by maxleiko** [comment]
Nope, not exactly. Something like that:  

**applyCmds == false**  
- build model from sintefboard
- make it available for pull
- **do not** send adaptations back to sintefboard (if any)

**applyCmds == true**  
- build model from sintefboard
- make it available for pull
- send adaptations back to sintefboard (if any)

**Comment by sdalgard** [comment]
I am not sure this fits with all future use cases.
Anyhow I think we can tweek that later.

I will try to get "applyCmds == false" to work first
According to my initial trace I provided there are some issues there.

**Comment by maxleiko** [comment]
Can we close this ?

**Comment by sdalgard** [comment]
Yes, we can handle this as part of the "way forward" discussion
